name: look around

on: 
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          sudo apt install tor
          npm install -g @treehouses/cli
          treehouses version
          sudo treehouses tor add 22
          sudo treehouses tor
          sudo treehouses tor list
          sudo treehouses tor notice now
          treehouses sshkey github adduser dogi
          echo "shh only dreams"
          sleep 1200
            
