name: look around

on: 
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: open sesame
        env:
          DEBIAN_FRONTEND: noninteractive
          TERM: xterm
          NOSPIN: "1"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends tor
          npm install --global @treehouses/cli
          treehouses version
          sudo -E treehouses tor add 22 2>&1 | sed -r $'s/\x1B\\[[0-9;?]*[A-Za-z]//g; s/[\x08\r]//g'
          sudo -E treehouses tor 2>&1 | sed -r $'s/\x1B\\[[0-9;?]*[A-Za-z]//g; s/[\x08\r]//g'
          sudo -E treehouses tor list 2>&1 | sed -r $'s/\x1B\\[[0-9;?]*[A-Za-z]//g; s/[\x08\r]//g'
          sudo -E treehouses tor notice now 2>&1 | sed -r $'s/\x1B\\[[0-9;?]*[A-Za-z]//g; s/[\x08\r]//g'
          sudo -E treehouses sshkey github adduser dogi 2>&1 | sed -r $'s/\x1B\\[[0-9;?]*[A-Za-z]//g; s/[\x08\r]//g'
          echo "shh only dreams"
