name: look around

on: 
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: open sesame
        env:
          DEBIAN_FRONTEND: noninteractive
          TERM: xterm
          NOSPIN: "1"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends tor
          npm install --global @treehouses/cli
          treehouses version
          sudo treehouses tor add 22
          treehouses tor
          treehouses tor list
          sudo treehouses tor notice now
          treehouses sshkey github adduser dogi
          echo "shh only dreams"
